# Generated by Django 5.2.3 on 2025-07-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
